server:
    port: 9797
spring:
    datasource:
        password: yiman
        url: jdbc:postgresql://localhost:5433/postgres
        username: postgres
    jpa:
        hibernate:
            ddl-auto: validate
        show-sql: true
